### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by alfacool** [storybookjs/addon-styling#73]
hi,, i just installed storybook to my angular project (angular16), and i tried to Integrate the sass using the guide from https://storybook.js.org/recipes/sass/ 

but i received and Error: Cannot read properties of undefined (reading 'replace') after registering the addons 

```
addons: [
    '@storybook/addon-essentials',
    {
      name: '@storybook/addon-styling',
      options: {
        sass: {
          // Require your Sass preprocessor here
          implementation: require('sass'),
        },
      },
    },
  ],
```

after reading the documentations i saw the warning 

![image](https://github.com/storybookjs/addon-styling/assets/37301399/f1958eb5-f2e0-43c1-938f-96e5ea252668)

so that means i cant use the addons? how to integrate the sass to SB ? whenever i tried to import the sass into preview.ts it keep telling me additional loader needed 

thanks in advance

**Comment by Integrayshaun** [comment]
Hey @alfacool 

Instead of importing your sass into `preview.ts` add it to the storybook task in your `angular.json` file like so:

```json
{
  "storybook": {
    "builder": "@storybook/angular:start-storybook",
    "options": {
      "browserTarget": "my-default-project:build",
      "styles": ["path/to/styles.sass"]
    }
  }
}
```

There's more information that you can read on the [styling & css docs page for Angular](https://storybook.js.org/docs/angular/configure/styling-and-css#styles-arent-being-applied-with-angular)
